Repository saiichihashimoto/sanity-typed, pull requests merged in 2023-05, with the labels that each got.

#2 fix(schema-builder): migrating from https://github.com/saiichihashimo…
  .eslintrc
  package-lock.json
  package.json
  packages/schema-builder/README.md
  packages/schema-builder/package.json
  packages/schema-builder/src/array/index.spec.ts
  packages/schema-builder/src/array/index.ts
  packages/schema-builder/src/block/index.spec.ts
  packages/schema-builder/src/block/index.ts
  packages/schema-builder/src/boolean/index.spec.ts
  packages/schema-builder/src/boolean/index.ts
  packages/schema-builder/src/builder.ts
  packages/schema-builder/src/date/index.spec.ts
  packages/schema-builder/src/date/index.ts
  packages/schema-builder/src/datetime/index.spec.ts
  packages/schema-builder/src/datetime/index.ts
  packages/schema-builder/src/document/index.spec.ts
  packages/schema-builder/src/document/index.ts
  packages/schema-builder/src/field/index.ts
  packages/schema-builder/src/file/index.spec.ts
  packages/schema-builder/src/file/index.ts
  packages/schema-builder/src/geopoint/index.spec.ts
  packages/schema-builder/src/geopoint/index.ts
  packages/schema-builder/src/image/index.spec.ts
  packages/schema-builder/src/image/index.ts
  packages/schema-builder/src/index.ts
  packages/schema-builder/src/list/index.ts
  packages/schema-builder/src/number/index.spec.ts
  packages/schema-builder/src/number/index.ts
  packages/schema-builder/src/object/index.spec.ts
  packages/schema-builder/src/object/index.ts
  packages/schema-builder/src/objectNamed/index.spec.ts
  packages/schema-builder/src/objectNamed/index.ts
  packages/schema-builder/src/reference/index.spec.ts
  packages/schema-builder/src/reference/index.ts
  packages/schema-builder/src/slug/index.spec.ts
  packages/schema-builder/src/slug/index.ts
  packages/schema-builder/src/string/index.spec.ts
  packages/schema-builder/src/string/index.ts
  packages/schema-builder/src/test-utils.ts
  packages/schema-builder/src/text/index.spec.ts
  packages/schema-builder/src/text/index.ts
  packages/schema-builder/src/types.ts
  packages/schema-builder/src/url/index.spec.ts
  packages/schema-builder/src/url/index.ts
  packages/schema-builder/tsconfig.json
Labels: automerge

#3 can the tsconfig be private?
  packages/tsconfig/package.json
Labels: automerge

#4 fix(description): package.json description for @sanity-typed/schema-builder
  README.md
  packages/schema-builder/README.md
  packages/schema-builder/package.json
Labels: automerge

#5 fix(description): package.json description for @sanity-typed/schema-builder
  packages/schema-builder/src/index.ts
Labels: automerge

#6 renamed .spec.ts to .test.ts
  packages/schema-builder/src/array/index.test.ts
  packages/schema-builder/src/block/index.test.ts
  packages/schema-builder/src/boolean/index.test.ts
  packages/schema-builder/src/date/index.test.ts
  packages/schema-builder/src/datetime/index.test.ts
  packages/schema-builder/src/document/index.test.ts
  packages/schema-builder/src/file/index.test.ts
  packages/schema-builder/src/geopoint/index.test.ts
  packages/schema-builder/src/image/index.test.ts
  packages/schema-builder/src/number/index.test.ts
  packages/schema-builder/src/object/index.test.ts
  packages/schema-builder/src/objectNamed/index.test.ts
  packages/schema-builder/src/reference/index.test.ts
  packages/schema-builder/src/slug/index.test.ts
  packages/schema-builder/src/string/index.test.ts
  packages/schema-builder/src/text/index.test.ts
  packages/schema-builder/src/url/index.test.ts
Labels: automerge

#7 use expectType instead of `type Assertions = []`
  .eslintrc
  packages/schema-builder/src/array/index.test.ts
  packages/schema-builder/src/block/index.test.ts
  packages/schema-builder/src/boolean/index.test.ts
  packages/schema-builder/src/date/index.test.ts
  packages/schema-builder/src/datetime/index.test.ts
  packages/schema-builder/src/document/index.test.ts
  packages/schema-builder/src/file/index.test.ts
  packages/schema-builder/src/geopoint/index.test.ts
  packages/schema-builder/src/image/index.test.ts
  packages/schema-builder/src/number/index.test.ts
  packages/schema-builder/src/object/index.test.ts
  packages/schema-builder/src/objectNamed/index.test.ts
  packages/schema-builder/src/reference/index.test.ts
  packages/schema-builder/src/slug/index.test.ts
  packages/schema-builder/src/string/index.test.ts
  packages/schema-builder/src/test-utils.ts
  packages/schema-builder/src/text/index.test.ts
  packages/schema-builder/src/url/index.test.ts
Labels: automerge

#8 push test-utils into it's own package
  package-lock.json
  packages/schema-builder/package.json
  packages/schema-builder/src/array/index.test.ts
  packages/schema-builder/src/block/index.test.ts
  packages/schema-builder/src/boolean/index.test.ts
  packages/schema-builder/src/date/index.test.ts
  packages/schema-builder/src/datetime/index.test.ts
  packages/schema-builder/src/document/index.test.ts
  packages/schema-builder/src/file/index.test.ts
  packages/schema-builder/src/geopoint/index.test.ts
  packages/schema-builder/src/image/index.test.ts
  packages/schema-builder/src/number/index.test.ts
  packages/schema-builder/src/object/index.test.ts
  packages/schema-builder/src/objectNamed/index.test.ts
  packages/schema-builder/src/reference/index.test.ts
  packages/schema-builder/src/slug/index.test.ts
  packages/schema-builder/src/string/index.test.ts
  packages/schema-builder/src/test-utils.ts
  packages/schema-builder/src/text/index.test.ts
  packages/schema-builder/src/url/index.test.ts
  packages/test-utils/package.json
  packages/test-utils/src/index.ts
  packages/test-utils/tsconfig.json
Labels: automerge

#11 @sanity-typed/types
  .eslintrc
  package-lock.json
  packages/test-utils/package.json
  packages/test-utils/src/index.test.ts
  packages/test-utils/src/index.ts
  packages/types/package.json
  packages/types/src/index.test.ts
  packages/types/src/index.ts
  packages/types/src/utils.ts
  packages/types/tsconfig.json
Labels: automerge

#12 schema-builder label
  .github/settings.yml
Labels: automerge

#25 adding types label
  .github/settings.yml
Labels: automerge

#26 feat(arrays): adds _key to objects in arrays
  packages/types/src/index.test.ts
  packages/types/src/index.ts
Labels: automerge, types

#27 copying in a bunch of @sanity/types tests
  .eslintrc
  packages/test-utils/src/index.test.ts
  packages/test-utils/src/index.ts
  packages/types/src/index.test.ts
  packages/types/src/index.ts
Labels: automerge, types

#28 fix(docs): correcting typescript example
  packages/schema-builder/README.md
Labels: schema-builder

#32 removing @sanity/types tests
  packages/test-utils/src/index.ts
  packages/types/src/index.test.ts
  packages/types/src/index.ts
Labels: automerge, types

#33 fix(name): defineField and defineType should always infer the literal name
  packages/types/src/index.test.ts
  packages/types/src/index.ts
Labels: automerge, types

#34 import expect in tests
  packages/types/src/index.test.ts
Labels: automerge, types

#35 fix(fields): fields should be optional by default
  packages/types/src/index.test.ts
  packages/types/src/index.ts
Labels: automerge, types
